### ISSUE TITLE
Trainer icon in different locations before and after battle

### ISSUE THREAD

**Issue by howey** [dannye/pokered-gen-II#2]
When you fight a trainer, the following things should happen:
1. A picture of the trainer should appear across from your character at the start of the battle
2. If you won the battle, a picture of the trainer should appear in the same spot as Step 1.

In this case, the trainer picture is in a different spot in Step 2. The trainer picture is too far to the right by maybe 15 pixels. For large trainer pictures, some of the picture goes off of the screen. This happens with every trainer battle. Using "My OldBoy" emulator for Android.

Beginning battle:
![pokered_1469577135744](https://cloud.githubusercontent.com/assets/4777515/17281799/42c6e338-5764-11e6-9848-eab4396d4a71.png)

Ending battle, shifted to right:
![pokered_1469577198354](https://cloud.githubusercontent.com/assets/4777515/17281800/42c9c6ca-5764-11e6-8992-92bbece96495.png)

**Comment by dannye** [comment]
This is in fact the original behavior of both gen 1 and gen 2.

**Comment by howey** [comment]
Really? It's been years since I've played the originals. I guess I forgot.

Thank you for the quick response.

Dylan
